### ISSUE TITLE
Possible bug: object/xml G_TS837_2400|A_PWK/G_TS837_2400_1|A_PWK_2

### ISSUE THREAD

**Issue by kjsdad** [DonZoeggerle/ediFabric#19]
This question pertains to both of these paths
 
G_TS837_2400|A_PWK
G_TS837_2400_1|A_PWK_2
 
Each of these has nodes S_PWK_LineSupplementalInformation and S_PWK_DurableMedicalEquipmentCertificateofMedicalNecessityIndicator.  The DME is never being used even though I have a PWK segment with a CT qualifier in the EDI file.  The enumeration being used by the DME node only has the CT code in it, however, the enumeration being used by the Supplemental segment also has a CT qualifier in it.  In the 4010 the CT qualifier in the PWK segment indicated DME certification, but on the 5010 it is in both places.  Are the enumerations correct or do I have a problem with how the data is laid out in my EDI file?  Below are the 2 lines I have in my EDI file for the PWK segments.
 
PWK*03*EM*1*0G*AC*2400S Attach Control Num*2400S Attach Control Num Description*>CH>CO>DM>NT>ON*A3
PWK*CT*AB*1*0G*C1*2400S DME Cert Number*2400S DME Cert Description*>CH>CO>DM>NT>ON*A3

**Comment by sbanner** [comment]
We are having this problem as well.  Can you look into it?  Thanks,

**Comment by DonZoeggerle** [comment]
Compared against the guidelines and the enums seem to be correct. I appreciate that with the same value 'CT' it will never hop onto the DME node as the parser currently disregards the max occurrence.
The only way to work around this is to enforce max occurrence checks and because the Supplemental segment has max occurs = 10, then if you have 11 PWK segments, it will allocate the first 10 to the Supplemental and the last one to DME.
Let me know your thoughts as this part of the guidelines is a bit grey.
Another approach would be for situations when only one of the Supplemental or DME is required. Then obviously you can swap the places of the segments as the first onw will always win.

**Comment by DonZoeggerle** [comment]
This is definitely a bug, I wasn't quite sure how to approach it. It looks like that the second element holds different values (as opposed to the first element in both allowing for 'CT'), so perhaps also checking the second values is the way to go.

**Comment by kjsdad** [comment]
When the attachment report type code is CT and attachment transmission code is (AB,AD,AF,AG,NS) The PWK is for DME.

**Comment by kjsdad** [comment]
Otherwise Supplemental
