### ISSUE TITLE
Trailing spaces

### ISSUE THREAD

**Issue by hayo1985** [DonZoeggerle/ediFabric#29]
I have received a file I try to parse, which has after the end of line separator from the edifact. a lot of trailing spaces and then the newline. When I try to parse this file I get:

Parameter name: ediSegment ---> System.ArgumentNullException: Value cannot be null.
Parameter name: ediSegment
   at EdiFabric.Framework.EdiHelper.GetSegmentName(String ediSegment, InterchangeContext interchangeContext)
   at EdiFabric.Framework.Envelopes.InterchangeLexer.Analyze()
   at EdiFabric.Framework.Envelopes.Edifact.Interchange.LoadFrom(Stream ediStream, String definitionsAssemblyName)

When i trim all the trailing spaces, it is parsed properly.

**Comment by DonZoeggerle** [comment]
Hi, could you please attach the broken file or at least the part with the trailing spaces ?
The parser does handle blank lines and trailing spaces so this can't be the problem. I suspect you have an empty segment. e.g. blank spaces ending with a semi quote ', which is in fact a blank segment. The message is then rendered as invalid because of that.

**Comment by DonZoeggerle** [comment]
Closing the issue (please reopen once you attach the sample file).
