### ISSUE TITLE
HIPAA 005010 Errata - Parse Error: Can't find a match for segment Name = AMT

### ISSUE THREAD

**Issue by BarryGreenspan** [DonZoeggerle/ediFabric#33]
005010X223A2
Parse error:  837 parser routine is failing when we try to process the AMT segment in the 2400 – Service Line Number loop from an  837i.  The data values in AMT01 and AMT02 may be invalid but would prefer not to fail the entire parsing since the structure is correct. Does the parser validate the data types / lengths etc of the data values in each respective field or just validate the structure? If data validation, is there a way to override or change this? Was able to parse the 837i file successfully using alternate parsers (x12parser and etasoft mini translator). Wondering if there is a similar option for edifabric or perhaps an older version with less restrictions on data elements?

**Comment by DonZoeggerle** [comment]
The Hipaa parser does use the first and second value in segments where these are defined, e.g. are enums. The purpose of this is to ensure the structure is preserved where there are multiple adjacent same name segments, e.g. AMT_1*CN, AMT_2*BG, AMT_3*45, etc. The parser needs to figure out which AMT (1, 2 or 3) to parse to as all the names are the same.
You can however override this in the class\xsd, by adding the data values to both the class and xsd. Te parser only validates structure when parsing.  Data validation only happens when you call Validate() against the xsd.
Sp extending the enum in the class and xsd with the extra data values is the way to go.

**Comment by DonZoeggerle** [comment]
Closing the issue
